# src/enums.py
from enum import Enum

class WeatherEnums:
    class LocationDataField(Enum):
        """Enum for accessing fields within the 'location' section of the weather API response."""
        NAME = "name"
        REGION = "region"
        COUNTRY = "country"
        LATITUDE = "lat"
        LONGITUDE = "lon"
        TIMEZONE_ID = "tz_id"
        LOCALTIME_EPOCH = "localtime_epoch"
        LOCALTIME = "localtime"

    class CurrentDataField(Enum):
        """Enum for accessing fields within the 'current' section of the weather API response."""
        LAST_UPDATED_EPOCH = "last_updated_epoch"
        LAST_UPDATED = "last_updated"
        TEMP_C = "temp_c"
        TEMP_F = "temp_f"
        IS_DAY = "is_day"
        CONDITION = "condition"
        WIND_MPH = "wind_mph"
        WIND_KPH = "wind_kph"
        WIND_DEGREE = "wind_degree"
        WIND_DIR = "wind_dir"
        PRESSURE_MB = "pressure_mb"
        PRESSURE_IN = "pressure_in"
        PRECIP_MM = "precip_mm"
        PRECIP_IN = "precip_in"
        HUMIDITY = "humidity"
        CLOUD = "cloud"
        FEELSLIKE_C = "feelslike_c"
        FEELSLIKE_F = "feelslike_f"
        VIS_KM = "vis_km"
        VIS_MILES = "vis_miles"
        UV = "uv"
        GUST_MPH = "gust_mph"
        GUST_KPH = "gust_kph"

    class ConditionDataField(Enum):
        """Enum for accessing fields within the 'condition' sub-section."""
        TEXT = "text"
        ICON = "icon"
        CODE = "code"

    class ForecastDayDataField(Enum):
        """Enum for accessing fields within each day's 'day' section in 'forecastday'."""
        DATE = "date"
        DATE_EPOCH = "date_epoch"
        DAY = "day"
        ASTRO = "astro"
        HOUR = "hour"

    class DayDataField(Enum):
        """Enum for accessing fields within the 'day' section of forecast day."""
        MAXTEMP_C = "maxtemp_c"
        MAXTEMP_F = "maxtemp_f"
        MINTEMP_C = "mintemp_c"
        MINTEMP_F = "mintemp_f"
        AVGTEMP_C = "avgtemp_c"
        AVGTEMP_F = "avgtemp_f"
        MAXWIND_MPH = "maxwind_mph"
        MAXWIND_KPH = "maxwind_kph"
        TOTALPRECIP_MM = "totalprecip_mm"
        TOTALPRECIP_IN = "totalprecip_in"
        TOTALSNOW_CM = "totalsnow_cm"
        AVGVIS_KM = "avgvis_km"
        AVGVIS_MILES = "avgvis_miles"
        AVGHUMIDITY = "avghumidity"
        DAILY_WILL_IT_RAIN = "daily_will_it_rain"
        DAILY_CHANCE_OF_RAIN = "daily_chance_of_rain"
        DAILY_WILL_IT_SNOW = "daily_will_it_snow"
        DAILY_CHANCE_OF_SNOW = "daily_chance_of_snow"
        CONDITION = "condition"
        UV = "uv"

    class AstroDataField(Enum):
        """Enum for accessing fields in the 'astro' section."""
        SUNRISE = "sunrise"
        SUNSET = "sunset"
        MOONRISE = "moonrise"
        MOONSET = "moonset"
        MOON_PHASE = "moon_phase"
        MOON_ILLUMINATION = "moon_illumination"
        IS_MOON_UP = "is_moon_up"
        IS_SUN_UP = "is_sun_up"

    class HourDataField(Enum):
        """Enum for accessing fields within each 'hour' entry."""
        TIME_EPOCH = "time_epoch"
        TIME = "time"
        TEMP_C = "temp_c"
        TEMP_F = "temp_f"
        IS_DAY = "is_day"
        CONDITION = "condition"
        WIND_MPH = "wind_mph"
        WIND_KPH = "wind_kph"
        WIND_DEGREE = "wind_degree"
        WIND_DIR = "wind_dir"
        PRESSURE_MB = "pressure_mb"
        PRESSURE_IN = "pressure_in"
        PRECIP_MM = "precip_mm"
        PRECIP_IN = "precip_in"
        HUMIDITY = "humidity"
        CLOUD = "cloud"
        FEELSLIKE_C = "feelslike_c"
        FEELSLIKE_F = "feelslike_f"
        WINDCHILL_C = "windchill_c"
        WINDCHILL_F = "windchill_f"
        HEATINDEX_C = "heatindex_c"
        HEATINDEX_F = "heatindex_f"
        DEWPOINT_C = "dewpoint_c"
        DEWPOINT_F = "dewpoint_f"
        WILL_IT_RAIN = "will_it_rain"
        CHANCE_OF_RAIN = "chance_of_rain"
        WILL_IT_SNOW = "will_it_snow"
        CHANCE_OF_SNOW = "chance_of_snow"
        VIS_KM = "vis_km"
        VIS_MILES = "vis_miles"
        GUST_MPH = "gust_mph"
        GUST_KPH = "gust_kph"
        UV = "uv"

# class TerrariumEnums:

# class AquariumEnums:

# class AssetsEnums: